### ISSUE TITLE
_get_facts unknown

### ISSUE THREAD

**Issue by Phill93** [napalm-automation-community/napalm-s350#24]
Hi,
this line throws an error https://github.com/napalm-automation-community/napalm-s350/blob/657bcc570ddcb0115e017fc2819aa38f95bde177/napalm_s350/s350.py#L200

I think you should call `_get_facts_parse_os_version` here

**Comment by qaxi** [comment]
Thank you,
my mistake, I did not check unit test before publishing ...
commited as https://github.com/napalm-automation-community/napalm-s350/commit/1ea7fbd241268d50742b442d2cf4e21b78a14fcf
