### ISSUE TITLE
get_interfaces_ip invalid output

### ISSUE THREAD

**Issue by Phill93** [napalm-automation-community/napalm-s350#40]
The interface part of the get_interfaces_ip method is wrong. The VLAN ID is cut off

Example:
IP 192.168.1.254 at VLAN 1
```
{'vlan': {'ipv4': {'192.168.1.254': {'prefix_length': 24}}}}
```

**Comment by Phill93** [comment]
switch output
```


    IP Address        I/F    I/F Status  Type   Redirect Status
                             admin/oper
------------------ --------- ---------- ------- -------- ------
0.0.0.0/32         vlan 1    UP/UP      DHCP    enable   Not
                                                         receiv
                                                         ed
192.168.1.254/24   vlan 1    UP/UP      Default enable   Valid


  Gateway IP Address        Activity status       Type
----------------------- ----------------------- --------

```

**Comment by qaxi** [comment]
It looks like SG500 is "strange" beast ...

May be we would have apply the same attitude as in #39 with detecting field width instead of spliting on " " ...

**Comment by Phill93** [comment]
The output is from an SG300-10. We have the problem with all models:
* https://github.com/napalm-automation-community/napalm-s350/blob/develop/test/unit/mocked_data/SG350X-48P-K9/show_ip_interface.txt
* https://github.com/napalm-automation-community/napalm-s350/blob/develop/test/unit/mocked_data/SG300-10/show_ip_interface.txt
