### ISSUE TITLE
 ERROR: setup.py is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

### ISSUE THREAD

**Issue by bvbek** [napalm-automation-community/napalm-s350#5]
How to actually correct install this community driver?

After git clone this repo to:
/usr/local/lib/python3.7/site-packages/napalm/
I try to use 
#pip install -e setup.py

I got error:
ERROR: setup.py is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

I got already installed:
napalm                   2.5.0
netmiko                  2.4.2
netaddr                  0.7.19

>>> from napalm import get_network_driver
>>> get_network_driver("s350")
<class 'napalm_s350.s350.S350Driver'>

any suggestion?

**Comment by cspeidel** [comment]
Have you tried to install from pip?
`pip install napalm-s350`

**Comment by cspeidel** [comment]
What about `python setup.py install`

**Comment by cspeidel** [comment]
Please use one of the following methods to install the driver:

Standard install:
```sh
$ pip install .                     # project in current directory
$ pip install path/to/project       # project in another directory
```
Editable install (development):
```sh
$ pip install -e .                     # project in current directory
$ pip install -e path/to/project       # project in another directory
```

**Comment by Cell20** [comment]
I get this error when I try to import bootstrap from an existing directory 

```
(todo) PS E:\Web Development\Django\Projects\dennis-ivy\lists> pip install -e 'D:\\Phython\\lib\\site-packages\\bootstra
p4'
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: D:\Phython\lib\site-pac
kages\bootstrap4
```

**Comment by Olafyd** [comment]
I got this error😢

/EplusEngine/EplusEngine is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
