### ISSUE TITLE
Bad authentication type - netbox

### ISSUE THREAD

**Issue by smalldatach** [napalm-automation-community/napalm-s350#52]
Hi

I installed the driver to netbox and changed the configuration.py like netbox documation said.
But i get the following error if it starts a querry:
_{"detail":"Error connecting to the device at 10.40.0.31: Bad authentication type; allowed types: ['']"}_

How i can send the username two times like i must do it when i login with normal ssh client?

thanks

**Comment by Phill93** [comment]
Hi,

please ensure you have `SSH User Authentication by Password` enabled.
Webinterface:
![Bildschirmfoto 2020-11-11 um 12 50 04](https://user-images.githubusercontent.com/1454797/98808507-842a9700-241c-11eb-80cf-781285afc03f.png)

CLI:
```
> conf
> ip ip ssh password-auth
```

**Comment by smalldatach** [comment]
100points - many thanks!!!
