### ISSUE TITLE
setup.py fails with pip>=10

### ISSUE THREAD

**Issue by cspeidel** [napalm-automation-community/napalm-s350#6]
We need a backwards-compatible fix to the dependency on pip.req in `setup.py` because it is moved to an internal function in pip 10.

```bash
Processing /home/travis/build/napalm-automation-community/napalm-s350
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-PWy1y1/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```

**Comment by zhengyang-lu** [comment]
I used the solution posted here: https://stackoverflow.com/a/49867265

**Comment by cspeidel** [comment]
> I used the solution posted here: https://stackoverflow.com/a/49867265

I committed a patch to my fork yesterday that doesn't rely on internal methods (pip._internal.req). We should not rely on internal methods because pip could change them at any time without notice.
https://github.com/cspeidel/napalm-s350/commit/9ede85bfd14c6ab373aa29840fff75a98ce65c17

Once I fix some of the other tox issues I'll push my develop branch up to the upstream develop branch.

**Comment by jasperla** [comment]
Note that several other drivers do use the private api ([ce](https://github.com/napalm-automation-community/napalm-ce/blob/master/setup.py#L6) and [hp-procurve](https://github.com/napalm-automation-community/napalm-hp-procurve/blob/master/setup.py#L5)), though I've taken the fix from [arubaos-switch](https://github.com/napalm-automation-community/napalm-arubaos-switch/blob/master/setup.py#L7) in #9.

**Comment by qaxi** [comment]
Resolved by merge
