### ISSUE TITLE
get_cdp_neighbors would be nice

### ISSUE THREAD

**Issue by smalldatach** [napalm-automation-community/napalm-s350#65]
### Short description
in addition to lldp, it would be nice to have cdp.

### Expected Behavior
my problem is that vmware swap device id and port id with lldp. with cdp the correct anwser is comming for device id and port id.

lldp:
  Port        Device ID          Port ID         System Name    Capabilities  TTL
--------- ----------------- ----------------- ----------------- ------------ -----
gi1/0/24  20:3a:07:XX:XX:XX       gi10                switch              B        112
te1/0/1        vmnic2       0c:c4:7a:XX:XX:XX           esxi                B        150

cdp:
    Device ID       Local        Adv  Time To Capability   Platform     Port ID
                          Interface  Ver.  Live
------------------ ----------- ---- ------- ---------- ------------ -----------

esxi                          gi1/0/10    2     129       S      VMware ESXi    vmnic1
   203a07XXXXXX     gi1/0/24    2     161      S I     Cisco                gi10

**Comment by qaxi** [comment]
Hi,
unfortunatelly get_cdp_neighbours is not suported in NAPALM ( https://napalm.readthedocs.io/en/latest/base.html ) 
Probable reason is that CDP is proprietary protocol. LLDP is IEEE standard 802.1AB .
We will not implement functions out of NAPALM standard.

To get CDP information you can use function 'cli' - currently work in progress.
