### ISSUE TITLE
lldp neighbors returns short interface names instead of full names

### ISSUE THREAD

**Issue by nniehoff** [napalm-automation-community/napalm-s350#74]
### Environment
Python version ('python3 --version'):  3.7.9
* Napalm version ('pip show napalm') : 3.2.0
* Napalm-s350 version ('pip show napalm-s350': 0.3.0
* Cisco SMB switch model (for example 'SG500-28-K9' or 'SG350X-48P-K9': SG300-28
* Napalm diagnostic output ('napalm --vendor s350 --user USER --debug HOSTNAME': available upon request

When I collect `get_lldp_neighbors_detail()` from the switch the dictionary is keyed off of the short interface names `gi1` instead of `gigabitethernet1`.  Based on the napalm documentation [here](https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_lldp_neighbors_detail) I expected this to be keyed off of the full name `gigabitethernet1` as shown in the output of `show run`.  Inspecting the output of `show lldp neighbors` from the switch, I see the short name as well.  This very well may just be a question if this is expected or not, maybe I'm the only one that expected the full names in which case I'll change my logic around a bit.

### Steps to Reproduce
1.  Run get_lldp_neighbors_detail against an SG300 series switch
2. Inspect the output

### Expected Behavior

I expected to see the dictionary from `get_lldp_neighbors_detail` to be keyed off of the full names of the interfaces `gigabitethernetX` versus the short name of `giX`

### Observed Behavior

The dictionary returned by `get_lldp_neighbors_detail` is keyed off of the short names of `giX` instead of `gigabitethernetX`.

**Comment by qaxi** [comment]
Yes, it is annoying as it complicates automation.
It bug.

It should be solved everywhere by using:
- canonical maps https://github.com/napalm-automation/napalm/blob/develop/napalm/base/canonical_map.py
- helper functions https://github.com/napalm-automation/napalm/blob/develop/napalm/base/helpers.py#L388

For example: https://github.com/napalm-automation/napalm/blob/develop/napalm/ios/ios.py#L937

**Comment by qaxi** [comment]
@nniehoff should be solved
a bit question is "vlan" interfaces ... should be canonicalized too?
