### ISSUE TITLE
0.4.1.1 is not published yet

### ISSUE THREAD

**Issue by SanderDelden** [napalm-automation-community/napalm-s350#91]
Hi,

Seems that 0.4.1.1 is not published to pypi.org yet. I need to upgrade to Napalm 4.1.0 but can't due to this package not being available yet.

Kind regards,
Sander

**Comment by qaxi** [comment]
Done by commit https://github.com/napalm-automation-community/napalm-s350/commit/1efdaaf26b7fd19312c217c5d8784ddbb39aa247
